language: c

os: linux
dist: trusty
group: stable
sudo: false

addons:
  apt:
    packages:
    - mesa-common-dev
    - libglu1-mesa-dev
    - libmad0-dev
    - libsdl1.2-dev
    - libsdl-image1.2-dev
    - libsdl-mixer1.2-dev
    - libsdl-ttf2.0-de
    - libogg-dev
    - mingw-w64
    - gcc-multilib

env:
- MAKE_CMD=./make-i386.sh
- MAKE_CMD=make
- MAKE_CMD=./cross-make-mingw.sh
#- MAKE_CMD=./cross-make-mingw64.sh

script: "$MAKE_CMD"

before_deploy: "./prepare_publish.sh"

deploy:
  provider: releases
  api_key:
    secure: GWXEhNh3o928uV8sgRtyWBv/5+DBNBrvRVgcjrqu9j99vjeFQakpsiz51YdKClRCer5Bv6O3gFjuGCWk0Y2p+HkS6ZnlmrZa2mOXlvfwJAQvH5/0GLeRzEz7MPZ6QUQ7JAWEp6XqdECv0kRuQI8oZdaqMNPSpz9o0FCmEk2g3MISqS1F/Udzu3gw2Z7nPc8rTI5BS92Ho2MCetNJpFmpvId0Qa6iuhZicwYLnFvc1IXL1+gt6oCsgNNF0Stggh3es7HYD3oJbIJoIjNEDarEA7gbgc1+PUbeBiAR8SrZr1SmgOFyz8AhLzTx164hJkDbjTz+z7FKwg2+o3yCIQ7PZexah1K2DrLGCWl5x2Cg0RRBQrZKoJDxdoecGgya+rkx47tis5OOP31g2uBIls7W7orSVBT/mYWkn6SXt/y45RxBO/Vi6x7TEbijRlL7BtBnA/Hvwn4OxBm3ogFWaFc71P4HH66mm5C4UHkZVh0itfrRgJRlFo3EYnAmlIqQAF09/otWcgUPXZZteSwRHh0cKkC8P/665LiJlA8yiVFYUoWnq/6275QcoC+TDWxsJSrUFkBrHnAQxik7pbqcYIE9KF9h9tTJG0YEE31dHdJP2KudrKms22GxDbu21yfZ3E99I+pB9wn+a2keaNi3DIh19D/cXFM1dOXYGk8rsl5gPIc=
  file_glob: true
  file: publish/*.zip
  skip_cleanup: true
  on:
    repo: MJLHThomassen/rpgxEF
    tags: true
