language: c

os: linux
dist: trusty
group": stable
sudo: false

addons:
  apt:
    packages:
    - mesa-common-dev
    - libglu1-mesa-dev
    - libmad0-dev
    - libsdl1.2-dev 
    - libsdl-image1.2-dev
    - libsdl-mixer1.2-dev
    - libsdl-ttf2.0-de
    - libogg-dev
    - mingw-w64 
    
install:
  - export CC="gcc -std=c99"

script: make
