language: c

os: linux
dist: trusty
group: stable
sudo: false

addons:
  apt:
    packages:  
    - mesa-common-dev
    - libglu1-mesa-dev
    - libmad0-dev
    - libsdl1.2-dev 
    - libsdl-image1.2-dev
    - libsdl-mixer1.2-dev
    - libsdl-ttf2.0-de
    - libogg-dev
    - mingw-w64
    - gcc-multilib

env:
  - MAKE_CMD=./make-i386.sh				# 32-bits Linux Binaries
  - MAKE_CMD=make						# 64-bits Linux Binaries
  - MAKE_CMD=./cross-make-mingw.sh		# 32-bits Windows Binaries
  - MAKE_CMD=./cross-make-mingw64.sh	# 64-bits Windows Binaries
  
script: "$MAKE_CMD"
